### ISSUE TITLE
On-Map toggle button backward color indicator

### ISSUE THREAD

**Issue by mbwatson** [RENCI/TerriaMap#100]
The colors indicating activity of the on-map button within layer cards are backward. See recordings showing this behavior on the initial layer at load-time and on a newly-added layer:

[Screencast from 2024-03-07 09-04-31.webm](https://github.com/RENCI/TerriaMap/assets/6019870/66d8a679-890f-4507-ad0b-92aa8f3808da)

[Screencast from 2024-03-07 09-06-38.webm](https://github.com/RENCI/TerriaMap/assets/6019870/67fb3705-86f3-4427-be30-871409e7520b)

**Comment by lstillwe** [comment]
This has been fixed, delivered, and tested successfully. Closing
