### ISSUE TITLE
Add buton to reset filtering dialog

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#25]
Currently no way to clear filter selections without closing/reopening the filter selection dialog.

**Comment by PhillipsOwen** [comment]
as of 5/24/23.

reset not working. Prior to testing i disabled the cache and refreshed the page.

selected a storm name.
hit the reset button.

nothing changed.

also selected more filters and tried to reset. dialog remains unchanged.

**Comment by lstillwe** [comment]
Please refer to issue #29 which indicates the reset but has been added, but it still has some issues.
