### ISSUE TITLE
Reset button is not fully operating

### ISSUE THREAD

**Issue by lstillwe** [RENCI/TerriaMap#29]
When the reset button in depressed in the layer filtering dialog, all select fields should return to unselected, and the list of filtered layers on the bottom should be cleared. 
This is also related to issue #28 which states that the list of filtered layers on the bottom should be cleared when the dialog is dismissed.

**Comment by lstillwe** [comment]
Noticed by Phil:
Currently, the filter dialog reset button seems to have no effect.

steps to reproduce: (note multiple ways to do this).
1.

open the filter dialog, select synoptic layer.
select a date on the calendar control.
hit the reset button, note that nothing happens.
open the filter dialog, select synoptic layer.
hit the search button, note there is data retrieved.
hit the reset button, note that nothing happens.
The expected behavior of the reset button is to clear all filter selections and previous results.

**Comment by scrummish** [comment]
1

**Comment by scrummish** [comment]
this has been fixed
