### ISSUE TITLE
Reordering the layers in the selected layer list

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#39]
The ordering of layers in the selected layer list is not functioning properly.

steps to reproduce:

1. select a number of synoptic layers from the filtering dialog. preferably with different titles to make following the action easier.
2. note that the topmost item is immovable.
3. note that moving the second and subsequent entries will only move up. 
4. note that when an item is moved up it always lands at the top of the list.

if you select the bottom most list item and attempt to move it up watch the action!

**Comment by scrummish** [comment]
This has been completed
