### ISSUE TITLE
Selecting tomorrows date in the filtering dialog.

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#40]
If tomorrows date is selected a not-so-informative error is shown.

"Failed to fetch form option data"

Steps to reproduce:
1. Select synoptic filtering.
2. Select tomorrows date. 
3. Behold the error message noted above.

As an added bonus, hit the search button. Vooosh, the form is reset to ground zero.

**Comment by scrummish** [comment]
completed
