### ISSUE TITLE
Needs enlargment

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#41]
this could be made a little larger.

this is the view of an observation detail. note that the actual data in the area contains a lot more information.

![image](https://github.com/RENCI/TerriaMap/assets/19691521/ce44017b-bd84-41d9-933a-2522b5d09c33)

why is this bound vertically?

this is the view of a layer detail.
![image](https://github.com/RENCI/TerriaMap/assets/19691521/04505f14-2525-4bd4-bfe8-b21385872f79)

**Comment by scrummish** [comment]
2

**Comment by lstillwe** [comment]
I believe this has been fixed - please review and close.

**Comment by PhillipsOwen** [comment]
extensive work has been done to this area which makes this issue irrelevant.
