### ISSUE TITLE
Selecting hurricane layers

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#47]
Just pops up a blank dialog that says "MetGet Hurricane Layer Selection".

probably an incomplete implementation that may need to be added to the task list.

![image](https://github.com/RENCI/TerriaMap/assets/19691521/06d04b62-fc00-480c-a3e5-ca2fb6a04faf)

**Comment by lstillwe** [comment]
Removed the other menu item for now.
