### ISSUE TITLE
Error message when the UI-data endpoint is unavailable.

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#49]
this morning the AWS load balancers went awry. when i was re configuring them this message appeared for the V2 UI (see below).

as it turns out the error message occurred because the UI data endpoint was not yet configured. what i want to point out is that the email address in the message is incorrect (help@example.com).

![image](https://github.com/RENCI/TerriaMap/assets/19691521/624682ec-7d50-4b88-a1d5-ecee1c4ed5c6)

**Comment by lstillwe** [comment]
We probably need to get a service email address for APSViz, is this possible?

**Comment by PhillipsOwen** [comment]
i will check!

**Comment by lstillwe** [comment]
Added new support email apsviz-help.renci.org to the config.json file
