### ISSUE TITLE
Observations graph gets removed when a new layer is added to the map

### ISSUE THREAD

**Issue by lstillwe** [RENCI/TerriaMap#50]
Steps to reproduce:

1. Click on an observations stations circle on the map.
2. Open the drawer and display the graph for that observations layer. Leave that graph on display in the drawer
3. Now use the filter dialog to add any type of new layer to the map. 
4. When the layer gets added the graph disappears. This is not the desired behavior - it should remain.

**Comment by lstillwe** [comment]
Only happens with newly added observation layers

**Comment by scrummish** [comment]
2

**Comment by scrummish** [comment]
@PhillipsOwen not able to replicate

**Comment by lstillwe** [comment]
This still needs to be fixed. Recommend for march deadline

**Comment by lstillwe** [comment]
Fixed in latest version - tested in Chrome
