### ISSUE TITLE
Help email link doesn't work

### ISSUE THREAD

**Issue by lstillwe** [RENCI/TerriaMap#51]
When clicking on the apsviz-help email link the following page comes up:

![Screen Shot 2023-08-16 at 7 57 02 PM](https://github.com/RENCI/TerriaMap/assets/1794116/b94bc152-f179-47be-a85d-d00f7ee5a24f)

**Comment by scrummish** [comment]
2

**Comment by PhillipsOwen** [comment]
This seems to be corrected in v0.2.24. closing...
