### ISSUE TITLE
Error occurs when adding to init URL query string (Version 0.2.17)

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#52]
i am adding the UI-nopp deploy to AWS.

when i set the initialazationURLs array to "initializationUrls": ["https://apsviz-ui-data.adcircprediction.org/get_ui_data_file?file_name=apsviz2.json&limit=1"]," startup fails with an error dialog. i verified that the ui-data URL returns catalog data.

i see this in the UI console log. as you can see there is some post op appending going on.

An error occurred while loading JSON file init/https:/apsviz-ui-data.adcircprediction.org/get_ui_data_file%3Ffile_name=apsviz2.json&limit=1.json.

**Comment by scrummish** [comment]
1

**Comment by lstillwe** [comment]
Unfortunately Terriajs code always appends '.json' to the end of the init url, if it is not already there.
This was fixed by Phil changing the url to always put the filename param at the end.
