### ISSUE TITLE
Filter dialog no longer returning data when filters selected (Version 0.2.17)

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#55]
after assigning filter parameters the select button has no effect (no data returned).

steps to reproduce:
- open the filter dialog, select synoptic layer.
- select a date on the calendar control.
- hit the select button.

note that nothing happens.

in fact, the only way to get layer data is to not select any filtering criteria at all.

**Comment by lstillwe** [comment]
This has been fixed
