### ISSUE TITLE
Data filter dialog (synoptic) reset not working properly (v0.2.19)

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#58]
like the title says.

steps to reproduce:
 - open the data filter dialog
 - select synoptic runs
 - enter in 1 or more selections
 - hit the select button
   - observe that a run list is shown and populated
 - hit the reset button
   - observe that the data value(s) did not reset.
   - observe that the run result list disappears
 - hit reset button again
   - observe that the last run result list reappears

**Comment by scrummish** [comment]
fixed
