### ISSUE TITLE
Hurricane icon/code/track layers are auto appearing without selection. (v0.2.19)

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#59]
The hurricane layers are not appearing in the filter selection list yet they are appearing on the UI, presumably when other hurricane layers are selected.

In addition, since the layers for the hurricane data (icons, cone, etc.) arent appearing in the selected layer drawer there is no way to remove them from the UI.

**Comment by lstillwe** [comment]
This is as designed and requested by Brian. There are no GeoServer layers to represent hurricane icon data. It is all retrieved in real time (from MetGet) when an ADCIRC hurricane layer is added to the map. The hurricane icons will be removed when all of the associated ADCIRC layers are removed. Although I am investigating some inconsistencies with that removal behavior currently. I will write a separate issue for that
