### ISSUE TITLE
No hurricane tracks on the UI (v0.2.19)

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#61]
There are no tracks shown along with the other hurricane layers on the UI.

i do see the track layer in the catalog data. it is just not being displayed on the UI

**Comment by lstillwe** [comment]
Is this V1 we are talking about? The custom code for getting MetGet hurricane track info was not added to V1.
Please close if this refers to the V1 UI

**Comment by PhillipsOwen** [comment]
nope, v0.2.19.

**Comment by lstillwe** [comment]
I see hurricane tracks on the AWS UI right now.

**Comment by PhillipsOwen** [comment]
all i see is the cone the icons, no track.
