### ISSUE TITLE
removed layers appear to be present in layer selection

### ISSUE THREAD

**Issue by mbwatson** [RENCI/TerriaMap#62]
in the layer selection dialog, removed layers appear to still be on the map.

in this recording, notice that the two deleted Idalia layers still appear to be on the map (they have a "-" icon instead of "+") when they show as options in the layer selection dialog.

![Peek 2023-08-31 15-02](https://github.com/RENCI/TerriaMap/assets/6019870/00106966-1f54-48fa-96b5-3e4a391fa3f7)

**Comment by mbwatson** [comment]
duplicate of #35

**Comment by lstillwe** [comment]
Close as a duplicate
