### ISSUE TITLE
Adjusting sliders using arrow key results in odd behaviour (v0.2.24)

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#63]
steps to reproduce:
 - bring up any image layer
 - select the layer
 - select the config tab
 - click the right hand side vertical slider
 - use the keyboard arrow keys to change the value
 - sit back and enjoy hours of fun with the elastic band behavior.

**Comment by scrummish** [comment]
@PhillipsOwen this has been fixed and ready for testing (upgrade/form-filter) branch

**Comment by PhillipsOwen** [comment]
This appears to work fine now. closing this issue...
