### ISSUE TITLE
Persistent filter selection results after removal from the selected layer list (v0.2.24)

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#72]
this is a close duplicate of #28 and #35:

A filter selection will remain in a selected state in the filter results even when the layer is removed. the selection remain even after hitting the reset button. steps to reproduce:

 - open the filter dialog
 - hit the search button for tropical runs (no other filter selections made)
 - select any image or observation layer shown in the results. (see the first image below)
 - remove the layer
 - hit the search button for tropical runs again (no other filter selections made)
 - scroll down to the layer selected and note that it remains selected (see the second image below)

![image](https://github.com/RENCI/TerriaMap/assets/19691521/54cda42c-3d4b-4dd1-a50e-7734febef1f6)
![image](https://github.com/RENCI/TerriaMap/assets/19691521/94395840-ba6a-440f-ba3f-cba8390e0364)

**Comment by lstillwe** [comment]
I reviewed this one and it has been fixed ... closing
