### ISSUE TITLE
Hurricane icons persist when no other layers are loaded (v0.2.24)

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#73]
The layer of hurricane icons remains although there are no other layers on the UI. steps to reproduce:
 - open the filter dialog
 - hit the search button for tropical runs (no other filter selections made)
 - select a observation layer
 - select an observation point
 - note that the hurricane track has appeared with the observation layer selected (see the first image below)
 - remove the observation layer
 - note the hurricane icons remain (see the second image below)

![image](https://github.com/RENCI/TerriaMap/assets/19691521/d34e0227-d336-4e0f-b7a9-4f85292b1781)
![image](https://github.com/RENCI/TerriaMap/assets/19691521/4c7ef919-dae9-4299-86a7-562a9008cc7f)

**Comment by lstillwe** [comment]
Propose closing this since hurricane layers are now a separate card that you can hide, show and delete?

**Comment by PhillipsOwen** [comment]
that sounds reasonable. closing...
