### ISSUE TITLE
Remove layers selected and selected layers text from the Drawer

### ISSUE THREAD

**Issue by lstillwe** [RENCI/TerriaMap#87]
Remove layers selected and selected layers text from the Drawer

**Comment by lstillwe** [comment]
Please also get rid of the "Feedback button" - Might be turned off and on in the config file.

**Comment by PhillipsOwen** [comment]
Corrected in PR #89

**Comment by PhillipsOwen** [comment]
i dont think this issue is relevant due to the way the hurricane tracks are layered onto the UI.

**Comment by lstillwe** [comment]
These updates have all been completed ... closing
